name       : cozy
version    : 0.5.5
release    : 2
source     :
    - https://github.com/geigi/cozy/archive/0.5.5.tar.gz : 9156592386aaa8ab6acddfad186b6427edad0d17808f5adb169dd1dc19727701
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : A modern audio book player
description: |
    Cozy is a modern audio book player for Linux using GTK+ 3
builddeps  :
    - pkgconfig(gtk+-3.0)
rundeps    :
    - gst-python
    - gstreamer-1.0-libav
    - gstreamer-1.0-plugins-good
    - mutagen
    - python3-dbus
    - python3-gobject
    - python-peewee
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
