name       : cozy
version    : 0.7.1
release    : 12
source     :
    - https://github.com/geigi/cozy/archive/0.7.1.tar.gz : 4e420a71d48805611a80f5fdaae23ca1a51f85ca703541ac8a52abdf3e9b9f99
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : A modern audio book player
description: |
    Cozy is a modern audio book player for Linux using GTK+ 3
builddeps  :
    - pkgconfig(gtk+-3.0)
    - mutagen
    - python-distro
    - python-gobject
    - python-peewee
rundeps    :
    - gst-python
    - gstreamer-1.0-libav
    - gstreamer-1.0-plugins-good
    - mutagen
    - python3-dbus
    - python-apsw
    - python-distro
    - python-gobject
    - python-peewee
    - python-pytz
    - python-requests
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
