name       : cozy
version    : 0.6.10
release    : 8
source     :
    - https://github.com/geigi/cozy/archive/0.6.10.tar.gz : 488876033927a3fc2b584cf483768f185a301ee9e3ae11acab69fa280a51a55d
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : A modern audio book player
description: |
    Cozy is a modern audio book player for Linux using GTK+ 3
builddeps  :
    - pkgconfig(gtk+-3.0)
rundeps    :
    - gst-python
    - gstreamer-1.0-libav
    - gstreamer-1.0-plugins-good
    - mutagen
    - python3-dbus
    - python3-gobject
    - python-distro
    - python-peewee
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
