name       : cozy
version    : 0.6.7
release    : 5
source     :
    - https://github.com/geigi/cozy/archive/0.6.7.tar.gz : af7f70ec2e09bae87d3640d72bdbc19856de964b571d0c803ada52e52fa1e466
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : A modern audio book player
description: |
    Cozy is a modern audio book player for Linux using GTK+ 3
builddeps  :
    - pkgconfig(gtk+-3.0)
rundeps    :
    - gst-python
    - gstreamer-1.0-libav
    - gstreamer-1.0-plugins-good
    - mutagen
    - python3-dbus
    - python3-gobject
    - python-peewee
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
