name       : cozy
version    : 1.2.0
release    : 18
source     :
    - https://github.com/geigi/cozy/archive/refs/tags/1.2.0.tar.gz : 5dbe1fb010bcc8b7a5b925aa2653808fdb14b58f87aad0cac8b0964d91eefc21
homepage   : https://cozy.sh/
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : A modern audio book player
description: |
    Cozy is a modern audio book player for Linux using GTK+ 3
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(libdazzle-1.0)
    - pkgconfig(libhandy-1)
    - desktop-file-utils
    - mutagen
    - python-distro
    - python-gobject
    - python-peewee
rundeps    :
    - granite
    - gst-python
    - gstreamer-1.0-libav
    - gstreamer-1.0-plugins-good
    - libdazzle
    - libhandy
    - mutagen
    - python3-dbus
    - python-distro
    - python-gobject
    - python-packaging
    - python-peewee
    - python-pytz
    - python-requests
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
